apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: cloud-controller-manager
build:
  artifacts:
  - image: kstiehl/anx-cloud-controller-manager
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - artifactOverrides:
          image: "kstiehl/anx-cloud-controller-manager"
        name: anx-ccm
        chartPath: chart
        imageStrategy:
          helm: {}
