// Code generated by MockGen. DO NOT EDIT.
// Source: go.anx.io/go-anxcloud/pkg (interfaces: API)

// Package gomockapi is a generated GoMock package.
package gomockapi

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	clouddns "go.anx.io/go-anxcloud/pkg/clouddns"
	ipam "go.anx.io/go-anxcloud/pkg/ipam"
	lbaas "go.anx.io/go-anxcloud/pkg/lbaas"
	test "go.anx.io/go-anxcloud/pkg/test"
	vlan "go.anx.io/go-anxcloud/pkg/vlan"
	vsphere "go.anx.io/go-anxcloud/pkg/vsphere"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// CloudDNS mocks base method.
func (m *MockAPI) CloudDNS() clouddns.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloudDNS")
	ret0, _ := ret[0].(clouddns.API)
	return ret0
}

// CloudDNS indicates an expected call of CloudDNS.
func (mr *MockAPIMockRecorder) CloudDNS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloudDNS", reflect.TypeOf((*MockAPI)(nil).CloudDNS))
}

// IPAM mocks base method.
func (m *MockAPI) IPAM() ipam.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IPAM")
	ret0, _ := ret[0].(ipam.API)
	return ret0
}

// IPAM indicates an expected call of IPAM.
func (mr *MockAPIMockRecorder) IPAM() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IPAM", reflect.TypeOf((*MockAPI)(nil).IPAM))
}

// LBaaS mocks base method.
func (m *MockAPI) LBaaS() lbaas.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LBaaS")
	ret0, _ := ret[0].(lbaas.API)
	return ret0
}

// LBaaS indicates an expected call of LBaaS.
func (mr *MockAPIMockRecorder) LBaaS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LBaaS", reflect.TypeOf((*MockAPI)(nil).LBaaS))
}

// Test mocks base method.
func (m *MockAPI) Test() test.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Test")
	ret0, _ := ret[0].(test.API)
	return ret0
}

// Test indicates an expected call of Test.
func (mr *MockAPIMockRecorder) Test() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Test", reflect.TypeOf((*MockAPI)(nil).Test))
}

// VLAN mocks base method.
func (m *MockAPI) VLAN() vlan.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VLAN")
	ret0, _ := ret[0].(vlan.API)
	return ret0
}

// VLAN indicates an expected call of VLAN.
func (mr *MockAPIMockRecorder) VLAN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VLAN", reflect.TypeOf((*MockAPI)(nil).VLAN))
}

// VSphere mocks base method.
func (m *MockAPI) VSphere() vsphere.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VSphere")
	ret0, _ := ret[0].(vsphere.API)
	return ret0
}

// VSphere indicates an expected call of VSphere.
func (mr *MockAPIMockRecorder) VSphere() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VSphere", reflect.TypeOf((*MockAPI)(nil).VSphere))
}
