// Code generated by MockGen. DO NOT EDIT.
// Source: go.anx.io/go-anxcloud/pkg/vsphere/powercontrol (interfaces: API)

// Package mockvsphere_powercontrol is a generated GoMock package.
package mockvsphere_powercontrol

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	powercontrol "go.anx.io/go-anxcloud/pkg/vsphere/powercontrol"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// AwaitCompletion mocks base method.
func (m *MockAPI) AwaitCompletion(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AwaitCompletion", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AwaitCompletion indicates an expected call of AwaitCompletion.
func (mr *MockAPIMockRecorder) AwaitCompletion(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AwaitCompletion", reflect.TypeOf((*MockAPI)(nil).AwaitCompletion), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockAPI) Get(arg0 context.Context, arg1 string) (powercontrol.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(powercontrol.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAPIMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAPI)(nil).Get), arg0, arg1)
}

// Set mocks base method.
func (m *MockAPI) Set(arg0 context.Context, arg1 string, arg2 powercontrol.Request) (powercontrol.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0, arg1, arg2)
	ret0, _ := ret[0].(powercontrol.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockAPIMockRecorder) Set(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockAPI)(nil).Set), arg0, arg1, arg2)
}
