apiVersion: v1
kind: ServiceAccount
metadata:
  name: anx-ccm-anx-cloud-controller-manager
  labels:
    app.kubernetes.io/name: anx-cloud-controller-manager
    app.kubernetes.io/instance: anx-ccm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anx-ccm-anx-cloud-controller-manager
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - create
      - get
      - list
      - watch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anx-ccm-anx-cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anx-ccm-anx-cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: anx-ccm-anx-cloud-controller-manager
    namespace: default
---
# Source: anx-cloud-controller-manager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anx-ccm-anx-cloud-controller-manager
  labels:
    app.kubernetes.io/name: anx-cloud-controller-manager
    app.kubernetes.io/instance: anx-ccm
    app.kubernetes.io/version: "0.0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: anx-cloud-controller-manager
      app.kubernetes.io/instance: anx-ccm
  template:
    metadata:
      annotations:
        providerconfig/checksum: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
      labels:
        app.kubernetes.io/name: anx-cloud-controller-manager
        app.kubernetes.io/instance: anx-ccm
    spec:
      serviceAccountName: anx-ccm-anx-cloud-controller-manager
      securityContext:
        {}
      containers:
        - name: anx-cloud-controller-manager
          command: ["/app/ccm"]
          args:
            - --cloud-provider=anx
            - --cloud-config=/etc/ccm/providerConfig.yaml
          volumeMounts:
            - mountPath: /etc/ccm
              name: provider-cfgmap
          securityContext:
            {}
          image: "anx-cr.io/anexia/anx-cloud-controller-manager:v0.1.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTPS
          resources:
            {}
      volumes:
        - name: provider-cfgmap
          secret:
            secretName: anx-ccm-anx-cloud-controller-manager-config
            optional: false
