// Code generated by MockGen. DO NOT EDIT.
// Source: go.anx.io/go-anxcloud/pkg/vsphere (interfaces: API)

// Package mockvsphere is a generated GoMock package.
package mockvsphere

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	info "go.anx.io/go-anxcloud/pkg/vsphere/info"
	powercontrol "go.anx.io/go-anxcloud/pkg/vsphere/powercontrol"
	provisioning "go.anx.io/go-anxcloud/pkg/vsphere/provisioning"
	search "go.anx.io/go-anxcloud/pkg/vsphere/search"
	vmlist "go.anx.io/go-anxcloud/pkg/vsphere/vmlist"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// Info mocks base method.
func (m *MockAPI) Info() info.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info")
	ret0, _ := ret[0].(info.API)
	return ret0
}

// Info indicates an expected call of Info.
func (mr *MockAPIMockRecorder) Info() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockAPI)(nil).Info))
}

// PowerControl mocks base method.
func (m *MockAPI) PowerControl() powercontrol.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PowerControl")
	ret0, _ := ret[0].(powercontrol.API)
	return ret0
}

// PowerControl indicates an expected call of PowerControl.
func (mr *MockAPIMockRecorder) PowerControl() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PowerControl", reflect.TypeOf((*MockAPI)(nil).PowerControl))
}

// Provisioning mocks base method.
func (m *MockAPI) Provisioning() provisioning.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provisioning")
	ret0, _ := ret[0].(provisioning.API)
	return ret0
}

// Provisioning indicates an expected call of Provisioning.
func (mr *MockAPIMockRecorder) Provisioning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provisioning", reflect.TypeOf((*MockAPI)(nil).Provisioning))
}

// Search mocks base method.
func (m *MockAPI) Search() search.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search")
	ret0, _ := ret[0].(search.API)
	return ret0
}

// Search indicates an expected call of Search.
func (mr *MockAPIMockRecorder) Search() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockAPI)(nil).Search))
}

// VMList mocks base method.
func (m *MockAPI) VMList() vmlist.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VMList")
	ret0, _ := ret[0].(vmlist.API)
	return ret0
}

// VMList indicates an expected call of VMList.
func (mr *MockAPIMockRecorder) VMList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VMList", reflect.TypeOf((*MockAPI)(nil).VMList))
}
