//go:build ignore
// +build ignore

// Code generated by mockery v2.53.6. DO NOT EDIT.

// NOTE: Legacy mockery-generated mocks have been removed from active use.
// This file is retained as a no-op placeholder to preserve history. Tests
// in this repository now use GoMock-generated mocks under
// `anx/provider/test/gomockapi` and related packages. To regenerate those
// mocks, see the //go:generate directives in `anx/provider/test/utils.go`.

package mocks

// Placeholder to indicate this legacy mock was intentionally removed.

// CloudDNS provides a mock function with no fields
func (_m *API) CloudDNS() clouddns.API {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloudDNS")
	}

	var r0 clouddns.API
	if rf, ok := ret.Get(0).(func() clouddns.API); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clouddns.API)
		}
	}

	return r0
}

// IPAM provides a mock function with no fields
func (_m *API) IPAM() ipam.API {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IPAM")
	}

	var r0 ipam.API
	if rf, ok := ret.Get(0).(func() ipam.API); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ipam.API)
		}
	}

	return r0
}

// LBaaS provides a mock function with no fields
func (_m *API) LBaaS() lbaas.API {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LBaaS")
	}

	var r0 lbaas.API
	if rf, ok := ret.Get(0).(func() lbaas.API); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(lbaas.API)
		}
	}

	return r0
}

// Test provides a mock function with no fields
func (_m *API) Test() test.API {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Test")
	}

	var r0 test.API
	if rf, ok := ret.Get(0).(func() test.API); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(test.API)
		}
	}

	return r0
}

// VLAN provides a mock function with no fields
func (_m *API) VLAN() vlan.API {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for VLAN")
	}

	var r0 vlan.API
	if rf, ok := ret.Get(0).(func() vlan.API); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vlan.API)
		}
	}

	return r0
}

// VSphere provides a mock function with no fields
func (_m *API) VSphere() vsphere.API {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for VSphere")
	}

	var r0 vsphere.API
	if rf, ok := ret.Get(0).(func() vsphere.API); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vsphere.API)
		}
	}

	return r0
}

// NewAPI creates a new instance of API. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *API {
	mock := &API{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
