// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	zone "github.com/anexia-it/go-anxcloud/pkg/clouddns/zone"
	mock "github.com/stretchr/testify/mock"
)

// CloudDNS is an autogenerated mock type for the API type
type CloudDNS struct {
	mock.Mock
}

// Zone provides a mock function with given fields:
func (_m *CloudDNS) Zone() zone.API {
	ret := _m.Called()

	var r0 zone.API
	if rf, ok := ret.Get(0).(func() zone.API); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(zone.API)
		}
	}

	return r0
}
