// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	info "go.anx.io/go-anxcloud/pkg/vsphere/info"
)

// Info is an autogenerated mock type for the API type
type Info struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, identifier
func (_m *Info) Get(ctx context.Context, identifier string) (info.Info, error) {
	ret := _m.Called(ctx, identifier)

	var r0 info.Info
	if rf, ok := ret.Get(0).(func(context.Context, string) info.Info); ok {
		r0 = rf(ctx, identifier)
	} else {
		r0 = ret.Get(0).(info.Info)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, identifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
