package mocks

import (
	acl "go.anx.io/go-anxcloud/pkg/lbaas/acl"
	backend "go.anx.io/go-anxcloud/pkg/lbaas/backend"
	bind "go.anx.io/go-anxcloud/pkg/lbaas/bind"
	frontend "go.anx.io/go-anxcloud/pkg/lbaas/frontend"
	loadbalancer "go.anx.io/go-anxcloud/pkg/lbaas/loadbalancer"
	rule "go.anx.io/go-anxcloud/pkg/lbaas/rule"
	server "go.anx.io/go-anxcloud/pkg/lbaas/server"

	genericresource "go.anx.io/go-anxcloud/pkg/genericresource"

	mock "github.com/stretchr/testify/mock"
)

// LBaaS is an autogenerated mock type for the API type
type LBaaS struct {
	mock.Mock
}

// ACL provides a mock function with given fields:
func (_m *LBaaS) ACL() genericresource.API[acl.ACL, acl.Definition] {
	ret := _m.Called()

	var r0 genericresource.API[acl.ACL, acl.Definition]
	if rf, ok := ret.Get(0).(func() genericresource.API[acl.ACL, acl.Definition]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(genericresource.API[acl.ACL, acl.Definition])
		}
	}

	return r0
}

// Backend provides a mock function with given fields:
func (_m *LBaaS) Backend() genericresource.API[backend.Backend, backend.Definition] {
	ret := _m.Called()

	var r0 genericresource.API[backend.Backend, backend.Definition]
	if rf, ok := ret.Get(0).(func() genericresource.API[backend.Backend, backend.Definition]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(genericresource.API[backend.Backend, backend.Definition])
		}
	}

	return r0
}

// Bind provides a mock function with given fields:
func (_m *LBaaS) Bind() genericresource.API[bind.Bind, bind.Definition] {
	ret := _m.Called()

	var r0 genericresource.API[bind.Bind, bind.Definition]
	if rf, ok := ret.Get(0).(func() genericresource.API[bind.Bind, bind.Definition]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(genericresource.API[bind.Bind, bind.Definition])
		}
	}

	return r0
}

// Frontend provides a mock function with given fields:
func (_m *LBaaS) Frontend() genericresource.API[frontend.Frontend, frontend.Definition] {
	ret := _m.Called()

	var r0 genericresource.API[frontend.Frontend, frontend.Definition]
	if rf, ok := ret.Get(0).(func() genericresource.API[frontend.Frontend, frontend.Definition]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(genericresource.API[frontend.Frontend, frontend.Definition])
		}
	}

	return r0
}

// LoadBalancer provides a mock function with given fields:
func (_m *LBaaS) LoadBalancer() genericresource.API[loadbalancer.Loadbalancer, loadbalancer.Definition] {
	ret := _m.Called()

	var r0 genericresource.API[loadbalancer.Loadbalancer, loadbalancer.Definition]
	if rf, ok := ret.Get(0).(func() genericresource.API[loadbalancer.Loadbalancer, loadbalancer.Definition]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(genericresource.API[loadbalancer.Loadbalancer, loadbalancer.Definition])
		}
	}

	return r0
}

// Rule provides a mock function with given fields:
func (_m *LBaaS) Rule() genericresource.API[rule.Rule, rule.Definition] {
	ret := _m.Called()

	var r0 genericresource.API[rule.Rule, rule.Definition]
	if rf, ok := ret.Get(0).(func() genericresource.API[rule.Rule, rule.Definition]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(genericresource.API[rule.Rule, rule.Definition])
		}
	}

	return r0
}

// Server provides a mock function with given fields:
func (_m *LBaaS) Server() genericresource.API[server.Server, server.Definition] {
	ret := _m.Called()

	var r0 genericresource.API[server.Server, server.Definition]
	if rf, ok := ret.Get(0).(func() genericresource.API[server.Server, server.Definition]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(genericresource.API[server.Server, server.Definition])
		}
	}

	return r0
}
