// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	search "github.com/anexia-it/go-anxcloud/pkg/vsphere/search"
	mock "github.com/stretchr/testify/mock"
)

// Search is an autogenerated mock type for the API type
type Search struct {
	mock.Mock
}

// ByName provides a mock function with given fields: ctx, name
func (_m *Search) ByName(ctx context.Context, name string) ([]search.VM, error) {
	ret := _m.Called(ctx, name)

	var r0 []search.VM
	if rf, ok := ret.Get(0).(func(context.Context, string) []search.VM); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]search.VM)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
