// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	info "github.com/anexia-it/go-anxcloud/pkg/vsphere/info"
	mock "github.com/stretchr/testify/mock"

	powercontrol "github.com/anexia-it/go-anxcloud/pkg/vsphere/powercontrol"

	provisioning "github.com/anexia-it/go-anxcloud/pkg/vsphere/provisioning"

	search "github.com/anexia-it/go-anxcloud/pkg/vsphere/search"
)

// VSphere is an autogenerated mock type for the API type
type VSphere struct {
	mock.Mock
}

// Info provides a mock function with given fields:
func (_m *VSphere) Info() info.API {
	ret := _m.Called()

	var r0 info.API
	if rf, ok := ret.Get(0).(func() info.API); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(info.API)
		}
	}

	return r0
}

// PowerControl provides a mock function with given fields:
func (_m *VSphere) PowerControl() powercontrol.API {
	ret := _m.Called()

	var r0 powercontrol.API
	if rf, ok := ret.Get(0).(func() powercontrol.API); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(powercontrol.API)
		}
	}

	return r0
}

// Provisioning provides a mock function with given fields:
func (_m *VSphere) Provisioning() provisioning.API {
	ret := _m.Called()

	var r0 provisioning.API
	if rf, ok := ret.Get(0).(func() provisioning.API); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provisioning.API)
		}
	}

	return r0
}

// Search provides a mock function with given fields:
func (_m *VSphere) Search() search.API {
	ret := _m.Called()

	var r0 search.API
	if rf, ok := ret.Get(0).(func() search.API); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(search.API)
		}
	}

	return r0
}
