//go:build ignore
// +build ignore

// Code generated by MockGen. DO NOT EDIT.
// Source: go.anx.io/go-anxcloud/pkg/lbaas (interfaces: API)

// Package mocklbaas is a generated GoMock package.
package mocklbaas

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	acl "go.anx.io/go-anxcloud/pkg/lbaas/acl"
	backend "go.anx.io/go-anxcloud/pkg/lbaas/backend"
	bind "go.anx.io/go-anxcloud/pkg/lbaas/bind"
	frontend "go.anx.io/go-anxcloud/pkg/lbaas/frontend"
	loadbalancer "go.anx.io/go-anxcloud/pkg/lbaas/loadbalancer"
	server "go.anx.io/go-anxcloud/pkg/lbaas/server"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// ACL mocks base method.
func (m *MockAPI) ACL() acl.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ACL")
	ret0, _ := ret[0].(acl.API)
	return ret0
}

// ACL indicates an expected call of ACL.
func (mr *MockAPIMockRecorder) ACL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ACL", reflect.TypeOf((*MockAPI)(nil).ACL))
}

// Backend mocks base method.
func (m *MockAPI) Backend() backend.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backend")
	ret0, _ := ret[0].(backend.API)
	return ret0
}

// Backend indicates an expected call of Backend.
func (mr *MockAPIMockRecorder) Backend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backend", reflect.TypeOf((*MockAPI)(nil).Backend))
}

// Bind mocks base method.
func (m *MockAPI) Bind() bind.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bind")
	ret0, _ := ret[0].(bind.API)
	return ret0
}

// Bind indicates an expected call of Bind.
func (mr *MockAPIMockRecorder) Bind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockAPI)(nil).Bind))
}

// Frontend mocks base method.
func (m *MockAPI) Frontend() frontend.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Frontend")
	ret0, _ := ret[0].(frontend.API)
	return ret0
}

// Frontend indicates an expected call of Frontend.
func (mr *MockAPIMockRecorder) Frontend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Frontend", reflect.TypeOf((*MockAPI)(nil).Frontend))
}

// LoadBalancer mocks base method.
func (m *MockAPI) LoadBalancer() loadbalancer.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadBalancer")
	ret0, _ := ret[0].(loadbalancer.API)
	return ret0
}

// LoadBalancer indicates an expected call of LoadBalancer.
func (mr *MockAPIMockRecorder) LoadBalancer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadBalancer", reflect.TypeOf((*MockAPI)(nil).LoadBalancer))
}

// Server mocks base method.
func (m *MockAPI) Server() server.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Server")
	ret0, _ := ret[0].(server.API)
	return ret0
}

// Server indicates an expected call of Server.
func (mr *MockAPIMockRecorder) Server() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Server", reflect.TypeOf((*MockAPI)(nil).Server))
}
