//go:build ignore
// +build ignore

// Code generated by MockGen. DO NOT EDIT.
// Source: go.anx.io/go-anxcloud/pkg/lbaas/loadbalancer (interfaces: API)

// Package mocklbaas_loadbalancer is a generated GoMock package.
package mocklbaas_loadbalancer

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "go.anx.io/go-anxcloud/pkg/apis/lbaas/v1"
	loadbalancer "go.anx.io/go-anxcloud/pkg/lbaas/loadbalancer"
	pagination "go.anx.io/go-anxcloud/pkg/pagination"
	param "go.anx.io/go-anxcloud/pkg/utils/param"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAPI) Get(arg0 context.Context, arg1, arg2 int) ([]loadbalancer.LoadBalancerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].([]loadbalancer.LoadBalancerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAPIMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAPI)(nil).Get), arg0, arg1, arg2)
}

// GetByID mocks base method.
func (m *MockAPI) GetByID(arg0 context.Context, arg1 string) (v1.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(v1.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAPIMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAPI)(nil).GetByID), arg0, arg1)
}

// GetPage mocks base method.
func (m *MockAPI) GetPage(arg0 context.Context, arg1, arg2 int, arg3 ...param.Parameter) (pagination.Page, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPage", varargs...)
	ret0, _ := ret[0].(pagination.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPage indicates an expected call of GetPage.
func (mr *MockAPIMockRecorder) GetPage(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPage", reflect.TypeOf((*MockAPI)(nil).GetPage), varargs...)
}

// NextPage mocks base method.
func (m *MockAPI) NextPage(arg0 context.Context, arg1 pagination.Page) (pagination.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextPage", arg0, arg1)
	ret0, _ := ret[0].(pagination.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextPage indicates an expected call of NextPage.
func (mr *MockAPIMockRecorder) NextPage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextPage", reflect.TypeOf((*MockAPI)(nil).NextPage), arg0, arg1)
}
