// Code generated by MockGen. DO NOT EDIT.
// Source: go.anx.io/go-anxcloud/pkg/clouddns (interfaces: API)

// Package mockclouddns is a generated GoMock package.
package mockclouddns

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	zone "go.anx.io/go-anxcloud/pkg/clouddns/zone"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// Zone mocks base method.
func (m *MockAPI) Zone() zone.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Zone")
	ret0, _ := ret[0].(zone.API)
	return ret0
}

// Zone indicates an expected call of Zone.
func (mr *MockAPIMockRecorder) Zone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Zone", reflect.TypeOf((*MockAPI)(nil).Zone))
}
