// Code generated by MockGen. DO NOT EDIT.
// Source: go.anx.io/go-anxcloud/pkg/vsphere/vmlist (interfaces: API)

// Package mockvsphere_vmlist is a generated GoMock package.
package mockvsphere_vmlist

import (
    context "context"
    reflect "reflect"

    gomock "github.com/golang/mock/gomock"
    vmlist "go.anx.io/go-anxcloud/pkg/vsphere/vmlist"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
    ctrl     *gomock.Controller
    recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
    mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
    mock := &MockAPI{ctrl: ctrl}
    mock.recorder = &MockAPIMockRecorder{mock}
    return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
    return m.recorder
}

// Get mocks base method.
func (m *MockAPI) Get(arg0 context.Context, arg1, arg2 int) ([]vmlist.VM, error) {
    m.ctrl.T.Helper()
    ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
    ret0, _ := ret[0].([]vmlist.VM)
    ret1, _ := ret[1].(error)
    return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAPIMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
    mr.mock.ctrl.T.Helper()
    return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAPI)(nil).Get), arg0, arg1, arg2)
}

